Feat: cancelled proposal
reserve-protocol/reserve-subgraph pull request #5
Opened 2024-01-16 14:18 UTC by JuampiRombola

https://www.notion.so/myreserve/add-Guardian-functionality-to-register-50a88ea8d55d475eb3ce97f68f26a7f0?pvs=25

2024-01-17 22:44 UTC, lcamargof requested changes
lgtm, only some leftover test code

2024-01-17 22:44 UTC, lcamargof commented on networks.json
> +      "address": "0x9C75314AFD011F22648ca9C655b61674e27bA4AC",
Revert this 🙏🏻

2024-01-18 16:39 UTC, lcamargof approved these changes

2024-01-18 16:39 UTC, JuampiRombola commented on src/common/utils/encoding.ts
> +  return Bytes.fromUint8Array(encodedBytes.slice(64))
@tbrent

2024-01-18 16:45 UTC, merged